Refactor workflow

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -88,7 +88,7 @@ jobs:
           mold_version="$(docker exec mold-builder "$OPTDIR/mold$BUILD_SUFFIX/bin/mold" -v)"
           echo "build_output=$build_output" | tee -a "$GITHUB_OUTPUT"
           echo "mold_version=$mold_version" | tee -a "$GITHUB_OUTPUT"
-      - name: Prepare release
+      - name: Tag release
         run: |
           date="$(date +%Y%m%d)"
           TAG_NAME=""
@@ -99,27 +99,31 @@ jobs:
             fi
           done
           if [[ -z "$TAG_NAME" ]]; then
+            echo "Error: too many revisions on $date. Aborting." >&2
             exit 1
           fi
-          RELEASE_TITLE="mold nightly builds $TAG_NAME"
-          NOTES_FILE="release-notes.txt"
-          cat <<EOF | tee -a "$NOTES_FILE"
-          - Nightly: \`${{ steps.build_mold_nightly.outputs.mold_version }}\`
-          - Stable ($MOLD_STABLE_VERSION): \`${{ steps.build_mold_stable.outputs.mold_version }}\`
-          EOF
+          git tag "$TAG_NAME"
+          git push origin "$TAG_NAME"
           echo "TAG_NAME=$TAG_NAME" | tee -a "$GITHUB_ENV"
+      - name: Generate release notes
+        run: |
+          RELEASE_TITLE="mold nightly builds $TAG_NAME"
+          NOTES_FILE="release-notes.md"
+          cat <<'EOF' | tee -a "$NOTES_FILE"
+          - Nightly (${{ steps.build_mold_nightly.outputs.build_output }}): `${{ steps.build_mold_nightly.outputs.mold_version }}`
+          - Stable (${{ steps.build_mold_stable.outputs.build_output }}): `${{ steps.build_mold_stable.outputs.mold_version }}`
+          EOF
           echo "RELEASE_TITLE=$RELEASE_TITLE" | tee -a "$GITHUB_ENV"
           echo "NOTES_FILE=$NOTES_FILE" | tee -a "$GITHUB_ENV"
       - name: Create release
         env:
           GITHUB_TOKEN: ${{ secrets.GH_TOKEN }}
         run: |
-          git tag "$TAG_NAME"
-          git push origin "$TAG_NAME"
           gh release create \
             --latest \
             --notes-file="$NOTES_FILE" \
             --title="$RELEASE_TITLE" \
+            --verify-tag \
             "$TAG_NAME" \
             "${{ steps.build_mold_nightly.outputs.build_output }}" \
             "${{ steps.build_mold_stable.outputs.build_output }}"
